### PR TITLE
fix(exec): args should not include quotes

### LINKED ISSUE #18: empty commit contains double quotes in commit message
The empty commit we need to check for permission includes double quotes `"` in its message.

screenshot 2018-12-10 at 10 47 18

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #18

### CODE REVIEW

**Comment by AndyOGo** [comment]
😆

**Comment by AndyOGo** [comment]
@LucaMele 
We need a way to test it.
I think a dummy repo would make sense 🤔

**Comment by LucaMele** [comment]
@AndyOGo yepp, thats a good idea

**Comment by AndyOGo** [comment]
Okidok I tracked it here #20

**Comment by LucaMele** [comment]
Thanks :)

**Pull request merged**
